#!/usr/bin/env bash
# Install `just` shell completions with recipe- and flag-value awareness
# for this repo (e.g. `just organize <TAB>` completes dirs/flags, and
# `--on-conflict <TAB>` offers skip|suffix|overwrite).
#
# Usage: bash scripts/setup-completions.sh [<shell>] [<root_dir>]
set -euo pipefail

shell="${1:-$(basename "${SHELL:-zsh}")}"
root_dir="${2:-.}"
root_dir="$(cd "$root_dir" && pwd)"

mkdir -p "$root_dir/.completions"

if [ "$shell" = "zsh" ]; then
    rc="$HOME/.zshrc"
    comp_file="$root_dir/.completions/just.zsh"

    stock=$(just --completions zsh)
    _stock_tmp=$(mktemp)
    echo "$stock" > "$_stock_tmp"

    python3 - "$comp_file" "$_stock_tmp" <<'PATCHER'
import sys

comp_file = sys.argv[1]
with open(sys.argv[2]) as f:
    stock = f.read()

new_block = '''            elif [[ $recipe ]]; then
                # Recipe-aware argument completions (auto-generated by setup-completions.sh)
                local prev=${words[CURRENT-1]}
                local cur=${words[CURRENT]}
                case $recipe in
                    organize|organize-apply)
                        case $prev in
                            --on-conflict)
                                local -a v=(${(f)"$(just list-values on-conflict 2>/dev/null)"})
                                (( ${#v} )) && _describe 'on-conflict' v && ret=0
                                ;;
                            --to|--plan|--from)
                                _files && ret=0
                                ;;
                            *)
                                if [[ $cur == -* ]]; then
                                    local -a flags=(
                                        '--to:library root'
                                        '--apply:execute the plan'
                                        '--dry-run:preview only (overrides --apply)'
                                        '--on-conflict:collision policy'
                                        '--plan:write the plan as JSON'
                                        '--from:apply/inspect a plan JSON'
                                    )
                                    _describe 'flag' flags && ret=0
                                else
                                    _files && ret=0
                                fi
                                ;;
                        esac
                        ;;
                    undo|organize-smoke)
                        ret=0
                        ;;
                    setup-completions)
                        local -a v=(${(f)"$(just list-values shell 2>/dev/null)"})
                        (( ${#v} )) && _describe 'shell' v && ret=0
                        ;;
                    list-values)
                        local -a v=(${(f)"$(just list-values dim 2>/dev/null)"})
                        (( ${#v} )) && _describe 'dimension' v && ret=0
                        ;;
                    scan|info|optimize|set-meta|set-cover|convert|standardize)
                        _files && ret=0
                        ;;
                    *)
                        _message "$(just --show $recipe 2>/dev/null)" && ret=0
                        ;;
                esac'''

lines = stock.split('\n')
result = []
i = 0
replaced = False
while i < len(lines):
    line = lines[i]
    if not replaced and 'elif [[ $recipe ]]; then' in line:
        result.append(new_block)
        i += 1
        while i < len(lines):
            if lines[i].strip() == 'else':
                break
            i += 1
        replaced = True
        continue
    result.append(line.replace('/ ##/:Args: }', '/ ##/:}'))
    i += 1

with open(comp_file, 'w') as f:
    f.write('\n'.join(result))
PATCHER
    rm -f "$_stock_tmp"

elif [ "$shell" = "bash" ]; then
    if [[ "$OSTYPE" == "darwin"* ]]; then rc="$HOME/.bash_profile"; else rc="$HOME/.bashrc"; fi
    comp_file="$root_dir/.completions/just.bash"

    just --completions bash > "$comp_file"

    cat >> "$comp_file" << 'BASH_COMP'

# Repo-specific recipe argument completions (auto-generated by setup-completions.sh)
_stacks_just_recipe_args() {
    local recipe="$1"; local cur="${COMP_WORDS[COMP_CWORD]}"; local prev="${COMP_WORDS[COMP_CWORD-1]}"
    case "$recipe" in
        organize|organize-apply)
            case "$prev" in
                --on-conflict) COMPREPLY=($(compgen -W "$(just list-values on-conflict 2>/dev/null)" -- "$cur")) ;;
                --to|--plan|--from) COMPREPLY=($(compgen -f -- "$cur")) ;;
                *)
                    if [[ "$cur" == -* ]]; then
                        COMPREPLY=($(compgen -W "--to --apply --dry-run --on-conflict --plan --from" -- "$cur"))
                    else
                        COMPREPLY=($(compgen -f -- "$cur"))
                    fi ;;
            esac ;;
        setup-completions) COMPREPLY=($(compgen -W "$(just list-values shell 2>/dev/null)" -- "$cur")) ;;
        list-values) COMPREPLY=($(compgen -W "$(just list-values dim 2>/dev/null)" -- "$cur")) ;;
        scan|info|optimize|set-meta|set-cover|convert|standardize) COMPREPLY=($(compgen -f -- "$cur")) ;;
    esac
}

if type _just &>/dev/null; then
    eval "_just_orig() $(declare -f _just | tail -n +2)"
    _just() {
        local recipe=""
        for ((idx=1; idx < COMP_CWORD; idx++)); do
            local w="${COMP_WORDS[idx]}"
            [[ "$w" == -* ]] && continue
            [[ -z "$recipe" ]] && recipe="$w"
        done
        if [[ -n "$recipe" ]]; then
            _stacks_just_recipe_args "$recipe"
            [[ ${#COMPREPLY[@]} -gt 0 ]] && return
        fi
        _just_orig
    }
    complete -o bashdefault -o default -F _just just
fi
BASH_COMP
else
    echo "Only zsh and bash are supported. Got: $shell" >&2
    exit 1
fi

source_line="[ -f \"$comp_file\" ] && source \"$comp_file\""

if grep -qF "$comp_file" "$rc" 2>/dev/null; then
    echo "Already installed in $rc"
else
    printf '\n# stacks/just completions\n%s\n' "$source_line" >> "$rc"
    echo "Added to $rc:"
    echo "  $source_line"
    echo ""
    echo "Completions available in new shells (or: source \"$comp_file\")."
fi
